global.oreTagsRemove = [
	//slag
	'thermal:slag',
	//coke
	'immersiveengineering:coke',
	'thermal:coal_coke',
//THERMAL
	//lead
	'thermal:lead_ingot',
	'thermal:lead_block',
	'thermal:raw_lead', 
	'thermal:raw_lead_block', 
	'thermal:lead_ore', 
	'thermal:deepslate_lead_ore',
	//silver
	'thermal:silver_ingot',
	'thermal:silver_block',
	'thermal:raw_silver', 
	'thermal:raw_silver_block', 
	'thermal:silver_ore', 
	'thermal:deepslate_silver_ore',
	//nickel
	'thermal:nickel_ingot',
	'thermal:nickel_block',
	'thermal:nickel_dust',
	'thermal:raw_nickel',
	'thermal:raw_nickel_block', 
	'thermal:nickel_ore', 
	'thermal:deepslate_nickel_ore',
	//steel
	'thermal:steel_ingot',
	'thermal:steel_block', 
	'thermal:steel_dust',
	//electrum
	'thermal:electrum_ingot',
	'thermal:electrum_block',
	'thermal:electrum_dust',
	//constantan
	'thermal:constantan_ingot',
	'thermal:constantan_block',
	'thermal:constantan_dust',
	//ender
	'thermal:ender_pearl_dust',
//CREATE-ADDITIONS
	//electrum
	'createaddition:electrum_ingot', 
	'createaddition:electrum_nugget',
//PNEUMATICCRAFT
	//copper
	'pneumaticcraft:copper_nugget', 
//EMBERS
	//copper
	'embers:copper_nugget', 
	//silver
	'embers:silver_nugget', 
	//lead
	'embers:lead_nugget', 
//CREATE
	//copper
	'create:copper_nugget', 
//AD-A
	//steel
	'ad_astra:steel_ingot', 
	'ad_astra:steel_nugget', 
	'ad_astra:steel_block',
//CAUPONA
	//lead
	'caupona:lead_block',
	'caupona:lead_ingot',
	'caupona:lead_nugget',
//EIDOLON
	//lead
	'eidolon:deep_lead_ore',
	'eidolon:deep_silver_ore',
	'eidolon:lead_block',
	'eidolon:lead_ingot',
	'eidolon:lead_nugget',
	'eidolon:lead_ore',
	'eidolon:raw_lead',
	'eidolon:raw_lead_block',
	//silver
	'eidolon:raw_silver',
	'eidolon:raw_silver_block',
	'eidolon:silver_block',
	'eidolon:silver_ingot',
	'eidolon:silver_nugget',
	'eidolon:silver_ore',
//GALOSPHERE
	//silver
	'galosphere:deepslate_silver_ore',
	'galosphere:raw_silver',
	'galosphere:raw_silver_block',
	'galosphere:silver_block',
	'galosphere:silver_ingot',
	'galosphere:silver_nugget',
	'galosphere:silver_ore',
//IE
	//nickel
	'immersiveengineering:nugget_nickel',
	//constantan
	'immersiveengineering:nugget_constantan',
	//electrum
	'immersiveengineering:nugget_electrum',
	//steel
	'immersiveengineering:nugget_steel',
	//copper
	'immersiveengineering:nugget_copper',
	//lead
	'immersiveengineering:dust_lead',
	'immersiveengineering:ingot_lead',
	'immersiveengineering:nugget_lead',
	'immersiveengineering:ore_lead',
	'immersiveengineering:deepslate_ore_lead',
	'immersiveengineering:deepslate_ore_silver',
	'immersiveengineering:raw_block_lead',
	'immersiveengineering:raw_lead',
	'immersiveengineering:storage_lead',
	//silver
	'immersiveengineering:dust_silver',
	'immersiveengineering:ingot_silver',
	'immersiveengineering:nugget_silver',
	'immersiveengineering:raw_silver',
	'immersiveengineering:ore_silver',
	'immersiveengineering:raw_block_silver',
	'immersiveengineering:storage_silver',
	//iron
	'immersiveengineering:dust_iron', 
	//sulfur
	'immersiveengineering:dust_sulfur', 
	//sulfur
	'immersiveengineering:dust_saltpeter', 
	//gold
	'immersiveengineering:dust_gold', 
	//copper
	'immersiveengineering:dust_copper',
//OCCULTISM
	//silver
	'occultism:raw_silver_block',
	'occultism:raw_silver',
	'occultism:silver_block',
	'occultism:silver_dust',
	'occultism:silver_ingot',
	'occultism:silver_nugget',
	'occultism:silver_ore',
	'occultism:silver_ore_deepslate',
//PARTS
	//RODS
	'ad_astra:iron_rod',
	'ad_astra:steel_rod',
	'createaddition:iron_rod',
	//WIRES
	'createaddition:copper_wire',
	'createaddition:electrum_wire',
	//PLATES
	'ad_astra:iron_plate',
	'ad_astra:steel_plate',
	'create:copper_sheet', 
	'create:iron_sheet', 
	'create:golden_sheet', 
	'createaddition:electrum_sheet', 
	'embers:copper_plate', 
	'embers:iron_plate', 
	'embers:lead_plate', 
	'embers:silver_plate',
	'thermal:copper_plate', 
	'thermal:iron_plate', 
	'thermal:gold_plate', 
	'thermal:electrum_plate', 
	'thermal:lead_plate', 
	'thermal:silver_plate', 
	'thermal:nickel_plate', 
	'thermal:constantan_plate', 
	'thermal:steel_plate',
	//DUSTS
	'bloodmagic:sulfur', 
	'bloodmagic:saltpeter', 
	'bloodmagic:ironsand', 
	'bloodmagic:goldsand', 
	'bloodmagic:coppersand', 
	'bloodmagic:coalsand',
	'eidolon:sulfur',
	'occultism:iron_dust', 
	'occultism:gold_dust', 
	'occultism:copper_dust',
	'occultism:obsidian_dust',
	'enderio:powdered_obsidian',
	'enderio:powdered_tin',
	'enderio:powdered_ender_pearl',
	'enderio:powdered_iron', 
	'enderio:powdered_gold', 
	'enderio:powdered_copper',
	'enderio:powdered_lapis_lazuli',
	'enderio:powdered_quartz',
	'alexscaves:sulfur_dust',
	'createaddition:diamond_grit',
	//SILICON
	'enderio:silicon',
	'tinyredstone:silicon',
	//SAWDUST
	'immersiveengineering:dust_wood',
	//OTHER
	'miniutilities:ender_dust',
	'malum:copper_nugget'
];

global.partDuplicates = [
	'industrialforegoing:iron_gear',
	'industrialforegoing:gold_gear', 
	'industrialforegoing:diamond_gear'
];