
#General settings
[general]
	#Use config instead of datapack
	use_config = true

	#List settings
	#Syntax: ["modid:block|weight"]
	#Example: ["minecraft:stone|2","minecraft:dirt|1"]
	#Forge tags are supported
	[general.lists]
		#Cobble gen
		block_list_cobble = ["minecraft:cobblestone|60", "masonry:diorite_cobbled|15", "masonry:granite_cobbled|15", "masonry:andesite_cobbled|15"]
		#Stone gen
		block_list_stone = ["minecraft:stone|30", "minecraft:granite|10", "minecraft:diorite|10", "minecraft:andesite|10", "minecraft:tuff|5", "minecraft:calcite|2", "quark:limestone|8", "quark:shale|8", "twigs:rhyolite|7", "twigs:schist|7", "twigs:silt|7", "forbidden_arcanus:darkstone|1", "create:limestone|6", "create:ochrum|6", "create:scoria|6", "create:scorchia|6", "create:veridium|6", "create:limestone|6", "create:limestone|6"]
		#Basalt gen
		block_list_basalt = ["minecraft:basalt|60", "minecraft:blackstone|60", "minecraft:netherrack|60", "twigs:bloodstone|40"]

		#Custom settings
		[general.lists.custom]
			#Custom generators
			#Syntax: [gen]
			#Gen: [type, block, list]
			#Type: cobblestone, stone
			#Block: resource location of the block below the generated block
			#List: see List settings
			#Examples:
			#custom_generators = [
			#   ["cobblestone", "minecraft:diamond_block", ["minecraft:diamond_block"]],
			#   ["cobblestone", "minecraft:dirt", ["forge:dirt"]],
			#   ["cobblestone", "minecraft:white_wool", ["minecraft:wool"]]]
			custom_generators = [["stone", "minecraft:amethyst_block", ["create:asurine|50", "create:crimsite|50"]]]

